/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.thoughtworks.com.demo;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class AppTest {
    @Test void appHandleStringWithSb() {
        App classUnderTest = new App();
        assertThat(classUnderTest.handleStringWithSb()).isNotNull();
    }

    @Test
    void should_get_handle_list_message() {
        App app = new App();
        assertThat(app.handleList()).isEqualTo("handle my list");
    }

    @Test
    void should_get_correct_list_length_after_remove_operation() {
        App app = new App();
        assertThat(app.handleRemoveListItem()).isEqualTo(3);
    }

    @Test
    void should_get_first_item_in_linked_list() {
        App app = new App();
        assertThat(app.getFirstListItem()).isEqualTo("apple");
    }

    @Test
    void should_get_union_collection_successfully() {
        ArrayList<String> fruit = new ArrayList<>(List.of("apple", "grape", "peach"));
        ArrayList<String> vegetable = new ArrayList<>(List.of("tomato", "bean"));
        App app = new App();

        assertThat(app.getUnionCollection(fruit, vegetable).size()).isEqualTo(5);
    }

    @Test
    void should_get_intersection_collection_successfully() {
        ArrayList<String> fruit = new ArrayList<>(List.of("apple", "grape", "peach"));
        ArrayList<String> vegetable = new ArrayList<>(List.of("apple", "tomato", "bean"));
        ArrayList<String> intersection = new ArrayList<>(List.of("apple"));
        App app = new App();

        assertThat(app.getIntersectionCollection(fruit, vegetable)).isEqualTo(intersection);
    }

    @Test
    void should_get_duplicate_substring_count_with_lang3() {
        App app = new App();
        assertThat(app.getDuplicateSubstringCount("i think that that fruit in that plate taste good", "that")).isEqualTo(3);
    }
}
